on: [push]

jobs:
  hello_world_job:
    runs-on:
      - self-hosted
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - uses: riccap/runner-tests/.github/actions/test1@main
